#!/bin/bash
#Soporte Remoto (SPR)
echo -e "\033[0;37m BIENVENIDO A SOPORTE ONLINE (APLICANDO FIX's)"
#Files Py
rm -rf /etc/VPS-ARCE/herramientas/speed.sh
rm -rf /etc/VPS-ARCE/herramientas/speedtest.py
cd /etc/VPS-ARCE/herramientas
# wget https://raw.githubusercontent.com/VArce89/VPS-ARCE/main/Install/SPR/code/speedtest_v1.tar >/dev/null 2>&1
# wget https://raw.githubusercontent.com/lacasitamx/VPSMX/master/code/speedtest_v1.tar >/dev/null 2>&1
tar -xf speedtest_v1.tar > /dev/null 2>&1 
rm -rf speedtest_v1.tar > /dev/null 2>&1
cd 
#Fix V2RAY
mkdir -p /etc/VPS-ARCE/v2ray > /dev/null 2>&1
echo -e "\033[0;92m VPSARCE INICIADO"
